### ISSUE TITLE
Crash error - Pimple - Call to a member function attach() on null

### ISSUE THREAD

**Issue by fufroma** [mduplouy/acme-web-manager#2]
Brand new fresh installation

```
PHP Fatal error:  Uncaught Error: Call to a member function attach() on null in /var/www/dev/acme-web-manager/vendor/pimple/pimple/src/Pimple/Container.php:164
Stack trace:
#0 /var/www/dev/acme-web-manager/vendor/octopuce/acmephpc/src/Octopuce/Acme/Client.php(81): Pimple\Container->factory(Object(Closure))
#1 /var/www/dev/acme-web-manager/vendor/solocreation/acme-php-service-provider/src/SoloCreation/AcmePhpServiceProvider.php(31): Octopuce\Acme\Client->__construct(Array)
#2 /var/www/dev/acme-web-manager/vendor/pimple/pimple/src/Pimple/Container.php(113): SoloCreation\AcmePhpServiceProvider->SoloCreation\{closure}(Object(Silex\Application))
#3 /var/www/dev/acme-web-manager/src/controllers.php(15): Pimple\Container->offsetGet('acme.client')
#4 [internal function]: {closure}(Object(Silex\Application))
#5 /var/www/dev/acme-web-manager/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array)
#6 /var/www/dev/acme-web-manager/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKer in /var/www/dev/acme-web-manager/vendor/pimple/pimple/src/Pimple/Container.php on line 164
```

Running PHP 7.0.9

**Comment by mduplouy** [comment]
I don't have this on PHP 5.5.38, gonna check on PHP 7

**Comment by fufroma** [comment]
Look like 9dcaed8973fdb75dd5488412b7f06fc57231964e fix this one too.

**Comment by mduplouy** [comment]
ok, seemed weird as this could not be php related :)
